data "discord_permission" "none" {
  # allow_extends = false
  # deny_extends  = false
}

# TODO Find allow_activity flag
# TODO Find manage event flag
data "discord_permission" "admin" {
  create_instant_invite = "allow"
  kick_members          = "allow"
  ban_members           = "allow"
  administrator         = "allow"
  manage_channels       = "allow"
  manage_guild          = "allow"
  add_reactions         = "allow"
  view_audit_log        = "allow"
  priority_speaker      = "allow"
  stream                = "allow"
  view_channel          = "allow"
  send_messages         = "allow"
  send_tts_messages     = "allow"
  manage_messages       = "allow"
  embed_links           = "allow"
  attach_files          = "allow"
  read_message_history  = "allow"
  mention_everyone      = "allow"
  use_external_emojis   = "allow"
  view_guild_insights   = "allow"
  connect               = "allow"
  speak                 = "allow"
  mute_members          = "allow"
  deafen_members        = "allow"
  move_members          = "allow"
  use_vad               = "allow"
  change_nickname       = "allow"
  manage_nicknames      = "allow"
  manage_roles          = "allow"
  manage_webhooks       = "allow"
  manage_emojis         = "allow"
  # TODO: update the provider
  # request_to_speak       = "allow"
  # manage_threads         = "allow"
  # create_public_threads  = "allow"
  # create_private_threads = "allow"
  # use_external_stickers  = "allow"
  # send_thread_messages   = "allow"
}

data "discord_permission" "modo" {
  create_instant_invite = "allow"
  kick_members          = "allow"
  ban_members           = "unset"
  administrator         = "unset"
  manage_channels       = "allow"
  manage_guild          = "unset"
  add_reactions         = "allow"
  view_audit_log        = "allow"
  priority_speaker      = "allow"
  stream                = "allow"
  view_channel          = "allow"
  send_messages         = "allow"
  send_tts_messages     = "unset"
  manage_messages       = "allow"
  embed_links           = "allow"
  attach_files          = "allow"
  read_message_history  = "allow"
  mention_everyone      = "allow"
  use_external_emojis   = "allow"
  view_guild_insights   = "allow"
  connect               = "allow"
  speak                 = "allow"
  mute_members          = "allow"
  deafen_members        = "allow"
  move_members          = "allow"
  use_vad               = "allow"
  change_nickname       = "allow"
  manage_nicknames      = "allow"
  manage_roles          = "allow"
  manage_webhooks       = "unset"
  manage_emojis         = "allow"
  # TODO: update the provider
  # request_to_speak       = "allow"
  # manage_threads         = "allow"
  # create_public_threads  = "allow"
  # create_private_threads = "allow"
  # use_external_stickers  = "allow"
  # send_thread_messages   = "allow"
}
